version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  mailtrain:
    env_file:
      - ./local.env
    build: .
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files

  admin:
    container_name: admin
    depends_on:
      - mysql
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 3001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mailtrain
    links:
      - mysql

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:

