version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  mailtrain:
    env_file:
      - ./local.env
    build:
      context: .
      dockerfile: Dockerfile-Develop
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - ./:/app
    - client-node-modules:/app/client/node_modules
    - server-node-modules:/app/server/node_modules
    - shared-node-modules:/app/shared/node_modules
    - zone-node-modules:/app/zone-mta/node_modules
    - mvis-node-modules:/app/mvis/client/node_modules
    - mvis2-node-modules:/app/mvis/server/node_modules
    - ivis-client-node-modules:/app/mvis/ivis-core/client/node_modules
    - ivis-server-node-modules:/app/mvis/ivis-core/server/node_modules
    - ivis-shared-node-modules:/app/mvis/ivis-core/shared/node_modules
    - ivis-embedding-node-modules:/app/mvis/ivis-core/embedding/node_modules

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  client-node-modules:
  server-node-modules:
  shared-node-modules:
  zone-node-modules:
  mvis-node-modules:
  mvis2-node-modules:
  ivis-client-node-modules:
  ivis-server-node-modules:
  ivis-shared-node-modules:
  ivis-embedding-node-modules:
