version: '3'

services:
  mysql:
    image: mariadb:10.4
    env_file:
      - ./development.env
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:4-xenial
    volumes:
    - mongo-data:/data/db

  mailtrain:
    depends_on:
      - mongo
      - mysql
      - redis
    env_file:
      - ./development.env
    build: .
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:

